name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create env files
      run: |
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" > .env

    - name: Login to DockerHub
      env:
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build --build-arg PORT=${{secrets.PROD_ENV_FILE}} -t jerinwilson/cicd-pipeline .

    - name: Push image to Dockerhub
      run: docker push jerinwilson/cicd-pipeline:latest
